In [25]:
import numpy as np
from linear_algebra import LinearAlgebra as la
from cosine_similarity import compute_cosine

In [5]:
vector = np.array([-2, 4, 9, 21])
result = la.compute_vector_length([vector])
print(round(result, 2))

23.28


In [7]:
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
print(round(la.compute_dot_product(v1, v2), 2))

4


In [8]:
x = np.array([[1, 2],
              [3, 4]])
k = np.array([1, 2])
print('result   \n', x.dot(k))

result   
 [ 5 11]


In [10]:
x = np.array([[-1, 2],
              [3, -4]])
k = np.array([1, 2])
print('result   \n', x @ k)

result   
 [ 3 -5]


In [11]:
m = np.array([[-1, 1, 1], 
              [0, -4, 9]])
v = np.array([0, 2, 1])
print(la.matrix_multi_vector(m, v))

[3 1]


In [12]:
m1 = np.array([[0, 1, 2], 
               [2, -3, 1]])
m2 = np.array([[1, -3],
               [6, 1],
               [0, -1]])
print(la.matrix_multi_matrix(m1, m2))

[[  6  -1]
 [-16 -10]]


In [15]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1],
               [2, 2, 2], 
               [3, 3, 3]])
print(m1 @ m2)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [20]:
m1 = np.eye(2)
m1 = np.reshape(m1, (-1, 4))[0]
m2 = np.array([[1, 1, 1, 1], 
               [2, 2, 2, 2], 
               [3, 3, 3, 3],
               [4, 4, 4, 4]])
print(m1 @ m2)

[5. 5. 5. 5.]


In [22]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1, 4), "F")[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

[29 29 29 29]


In [23]:
m1 = np.array([[-2, 6], [8, -4]])
result = la.inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


$$
A = 
\begin{bmatrix} 
0.9 & 0.2 \\ 
0.1 & 0.8 \
\end{bmatrix}
$$

## Eigenvalues:

$$det(A - \lambda I) = 0$$

$$
\begin{bmatrix} 
0.9 - \lambda & 0.2 \\ 
0.1 & 0.8 - \lambda 
\end{bmatrix} = 0
$$

$$(0.9 - \lambda)(0.8 - \lambda) - 0.02 = 0$$

$$\lambda_1 = 0.7, \lambda_2 = 1$$

## Eigenvectors:
For $\lambda_1 = 0.7$:

$$(A - \lambda I)v = 0$$

$$
\begin{bmatrix} 
0.9 - 0.7 & 0.2 \\ 
0.1 & 0.8 - 0.7 
\end{bmatrix} 
\begin{bmatrix} 
v_1 \\ v_2 
\end{bmatrix} = 0 
$$

$$
\begin{bmatrix} 
0.2 & 0.2 \\ 
0.1 & 0.1 
\end{bmatrix} 
\begin{bmatrix} 
v_1 \\ v_2 
\end{bmatrix} = 0 
$$

$$
\begin{bmatrix} 0.2 \\ 0.1 \end{bmatrix} v_1 + 
\begin{bmatrix} 0.2 \\ 0.1 \end{bmatrix} v_2 = 0
$$

$$v_1=-v_2$$
Therefore, eigenvector corresponding to $\lambda_1 = 0.7$ is:\
$v_1 = \begin{bmatrix} -1 \\ 1 \end{bmatrix}$


For $\lambda_2 = 1$:
$$(A - \lambda I)v = 0$$

$$
\begin{bmatrix} 
0.9 - 1 & 0.2 \\ 
0.1 & 0.8 - 1 
\end{bmatrix} 
\begin{bmatrix} 
v_1 \\ v_2 
\end{bmatrix} = 0 
$$

$$
\begin{bmatrix} 
-0.1 & 0.2 \\ 
0.1 & -0.2 
\end{bmatrix} 
\begin{bmatrix} 
v_1 \\ v_2 
\end{bmatrix} = 0 
$$

$$
\begin{bmatrix} -0.1 \\ 0.1 \end{bmatrix} v_1 + 
\begin{bmatrix} 0.2 \\ -0.2 \end{bmatrix} v_2 = 0
$$

$$v_1=2v_2$$
Therefore, eigenvector corresponding to $\lambda_2 = 1$ is:\
$v_2 = \begin{bmatrix} 2 \\ 1 \end{bmatrix}$

## Normalize:
$\lambda_1 = 0.7, \ v_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} -1 \\ 1 \end{bmatrix} = \begin{bmatrix} -0.707 \\ 0.707 \end{bmatrix}$


$\lambda_2 = 1, \ v_2 = \frac{1}{\sqrt{5}} \begin{bmatrix} 2 \\ 1 \end{bmatrix} = \begin{bmatrix} 0.894 \\ 0.447 \end{bmatrix}$

$v = 
\begin{bmatrix} 
-0.707 & 0.894 \\
0.707 & 0.447 \end{bmatrix}
$

In [24]:
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = la.compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


$x = \begin{bmatrix} 1\\2\\3\\4\end{bmatrix}, \ y = \begin{bmatrix} 1\\0\\3\\0\end{bmatrix}$

## Cosine Similarity
$x \cdot y = 1\cdot1+2\cdot0+3\cdot3+4\cdot0 = 10$\
$\|x\| = \sqrt{1^2 + 2^2 + 3^2 + 4^2} = \sqrt{1 + 4 + 9 + 16} = \sqrt{30}$

$\|y\| = \sqrt{1^2 + 0^2 + 3^2 + 0^2} = \sqrt{1 + 0 + 9 + 0} = \sqrt{10}$

$cs(x, y) = \frac{x \cdot y}{||x||||y||} = \frac{10}{\sqrt{30}\sqrt{10}} = 0.577$

In [26]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x, y)
print(round(result, 3))

0.577
