### Create 1D array

In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 10, 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Create 3x3 boolean array

In [5]:
arr = np.ones((3, 3)) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
arr = np.ones((3, 3), dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr = np.full((3, 3), fill_value=True, dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Filter odd numbers

In [9]:
arr = np.arange(0, 10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [12]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Reshape 1D to 2D

In [13]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Concatenate

In [15]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
c = np.concatenate([arr1, arr2], axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Repeat, tile

In [18]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [19]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
idx = np.where((a >= 5) & (a <= 10))
a[idx]

array([ 6,  9, 10])

### Vectorize

In [20]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
    
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)


array([6., 7., 9., 8., 9., 7., 5.])

In [21]:
np.where(a < b, b, a)

array([6, 7, 9, 8, 9, 7, 5])