In [1]:
import numpy as np
from logistic_regression_funcs import *

X = [[22.3, -1.5, 1.1, 1]]
theta = [0.1, -0.15, 0.3, -0.2]
predict(X, theta)

array([0.92988994])

In [2]:
y = np.array([1, 0, 0, 1])
y_hat = np.array([0.8, 0.75, 0.3, 0.95])
compute_loss(y_hat, y)

0.5043515376900958

In [5]:
X = np.array([[1, 2], [2, 1], [1, 1], [2, 2]])
y = np.array([0, 1, 0, 1])
y_hat = np.array([0.25, 0.75, 0.4, 0.8])
compute_gradient(X, y, y_hat)

array([-0.0625,  0.0625])

In [7]:
y = [1, 0, 1, 1]
y_hat = [0.85, 0.35, 0.9, 0.75]

def compute_accuracy(y, y_hat):
    return np.mean(np.round(y_hat) == y)

compute_accuracy(y, y_hat)

1.0

In [9]:
X = np.array([[1, 3], [2, 1], [3, 2], [1, 2]])
y = np.array([1, 0, 1, 1])
y_hat = np.array([0.7, 0.4, 0.6, 0.85])
compute_gradient(X, y, y_hat)


array([-0.2125, -0.4   ])